<?php

ini_set('session.cookie_domain','shopsapps.gobozu.com');
ini_set('session.gc_maxlifetime', 0);
ini_set('session.cookie_lifetime', 0);

session_set_cookie_params(0);

header('Cache-Control: no-cache, max-age=0, must-revalidate, no-store');
  header("Cache-Control: private, must-revalidate, max-age=0");
  header("Pragma: no-cache");
  header("Expires: Sat, 26 Jul 1997 05:00:00 GMT"); // A date in the past		

function NewGuid() 
{ 
	srand();
	$s = strtoupper(md5(uniqid(rand(),true))); 
	$guidText = 
		substr($s,0,8) . '-' . 
		substr($s,8,4) . '-' . 
		substr($s,12,4). '-' . 
		substr($s,16,4). '-' . 
		substr($s,20); 
	return $guidText;
}

function udefToStr($str)
{
	if (!isset($str) ) return "";
	if (is_null($str)) return "";
	return $str;
}

$pageRenderingEndTime=0;

function PreRenderPage()
{
	global $pageRenderingStartTime;
	global $pageRenderingEndTime;
	ob_start();
	$pageRenderingStartTime = microtime(TRUE);
}

function RenderPage()
{
	global $pageRenderingStartTime;
	global $pageRenderingEndTime;
	$page = ob_get_contents();
	ob_end_clean();
	$page = preg_replace('/[ ]{2,}|[\t]/', '', trim($page));
	$page = str_replace(array("\\\r\n", "\\\r"), " ", $page);
	$page = str_replace(array("\r\n", "\r"), " ", $page);
	echo $page;
	
	$pageRenderingEndTime = microtime(TRUE);
	$pageRenderingTime = ($pageRenderingEndTime - $pageRenderingStartTime) / 1000000;
	echo "<!-- gentime: ". $pageRenderingTime ." -->";
}

function SanitizeObject($object)
{
	//aplica trim a cada uno de sus atributos. Remueve Tags HTML ocasionales.
	foreach($object as $key=>$value)
	{
		if ( !is_array($object->$key) )
		{
			$object->$key = trim( strip_tags($value) );
		}
		else
		{
			foreach($object->$key as $arrkey=>$arrvalue)
			{
				//$object->$key->$arrkey = $this->SanitizeObject($arrvalue);
			}
		}
	}
	return $object;
}

function stripAccents($str)
{
	$unwanted_array = array(    'Š'=>'S', 'š'=>'s', 'Ž'=>'Z', 'ž'=>'z', 'À'=>'A', 'Á'=>'A', 'Â'=>'A', 'Ã'=>'A', 'Ä'=>'A', 'Å'=>'A', 'Æ'=>'A', 'Ç'=>'C', 'È'=>'E', 'É'=>'E',
								'Ê'=>'E', 'Ë'=>'E', 'Ì'=>'I', 'Í'=>'I', 'Î'=>'I', 'Ï'=>'I', 'Ñ'=>'N', 'Ò'=>'O', 'Ó'=>'O', 'Ô'=>'O', 'Õ'=>'O', 'Ö'=>'O', 'Ø'=>'O', 'Ù'=>'U',
								'Ú'=>'U', 'Û'=>'U', 'Ü'=>'U', 'Ý'=>'Y', 'Þ'=>'B', 'ß'=>'Ss', 'à'=>'a', 'á'=>'a', 'â'=>'a', 'ã'=>'a', 'ä'=>'a', 'å'=>'a', 'æ'=>'a', 'ç'=>'c',
								'è'=>'e', 'é'=>'e', 'ê'=>'e', 'ë'=>'e', 'ì'=>'i', 'í'=>'i', 'î'=>'i', 'ï'=>'i', 'ð'=>'o', 'ñ'=>'n', 'ò'=>'o', 'ó'=>'o', 'ô'=>'o', 'õ'=>'o',
								'ö'=>'o', 'ø'=>'o', 'ù'=>'u', 'ú'=>'u', 'û'=>'u', 'ý'=>'y', 'ý'=>'y', 'þ'=>'b', 'ÿ'=>'y', '"'=>' ', '\''=>' ' );
	$str = strtr( $str, $unwanted_array );
	return $str;	
}


function fHash($str)
{
	return strtoupper( uuid_make($str) );
}

function uuid_make($str)
{
	$string = md5($str . '_marce1234');
	$string = substr($string, 0, 8 ) .'-'.
	substr($string, 8, 4) .'-'.
	substr($string, 12, 4) .'-'.
	substr($string, 16, 4) .'-'.
	substr($string, 20);
	return $string;
}

function utf8ize($d) 
{
    if (is_array($d)) 
        foreach ($d as $k => $v) 
            $d[$k] = utf8ize($v);

     else if(is_object($d))
        foreach ($d as $k => $v) 
            $d->$k = utf8ize($v);

     else 
        return utf8_encode($d);

    return $d;
}

function jsonp_encode($obj, $callback, $callbackAdditionalArgs)
{
	//$obj2 = utf8ize($obj);
	//$obj = $obj2;
	
	if (trim($callback)!='')
	{
		http_response_code(200);
		
		if (trim($callbackAdditionalArgs)!='')
		{
			return $callback . '(' . json_encode($obj) . ', '.$callbackAdditionalArgs.');';
		}
		else
		{
			return $callback . '(' . json_encode($obj) . ');';
		}
	}
	else
	{
		return json_encode($obj);
	}
}


function SimilarityDistance($s1, $s2)
{
	return 1 / (similar_text($s1, $s2) + 1);
}

function Cmp($a, $b)
{
    return Sign($a->DistanceToSearch - $b->DistanceToSearch);
}

function Sign($number) 
{
	return $number / abs($number ?: 1);
}



function isValidEmail($email)
{ 
	return filter_var($email, FILTER_VALIDATE_EMAIL) !== false;
}







/*

$mime_types = array(
	'.3dm' => 'x-world/x-3dmf',
	'.3dmf' => 'x-world/x-3dmf',
	'.a' => 'octet-stream',
	'.aab' => 'x-authorware-bin',
	'.aam' => 'x-authorware-map',
	'.aas' => 'x-authorware-seg',
	'.abc' => 'text/vnd.abc',
	'.acgi' => 'text/html',
	'.afl' => 'video/animaflex',
	'.ai' => 'archivo postscript',
	'.aif' => 'audio/aiff',
	'.aif' => 'audio/x-aiff',
	'.aifc' => 'audio/aiff',
	'.aifc' => 'audio/x-aiff',
	'.aiff' => 'audio/aiff',
	'.aiff' => 'audio/x-aiff',
	'.aim' => 'x-aim',
	'.aip' => 'text/x-audiosoft-intra',
	'.ani' => 'x-navi-animation',
	'.aos' => 'x-nokia-9000-communicator-add-on-software',
	'.aps' => 'mime',
	'.arc' => 'octet-stream',
	'.arj' => 'arj',
	'.arj' => 'octet-stream',
	'.art' => 'image/x-jg',
	'.asf' => 'video/x-ms-asf',
	'.asm' => 'text/x-asm',
	'.asp' => 'text/asp',
	'.asx' => 'x-mplayer2',
	'.asx' => 'video/x-ms-asf',
	'.asx' => 'video/x-ms-asf-plugin',
	'.au' => 'audio/basic',
	'.au' => 'audio/x-au',
	'.avi' => 'x-troff-msvideo',
	'.avi' => 'video/avi',
	'.avi' => 'video/msvideo',
	'.avi' => 'video/x-msvideo',
	'.avs' => 'video/avs-video',
	'.bcpio' => 'x-bcpio',
	'.bin' => 'mac-binary',
	'.bin' => 'macbinary',
	'.bin' => 'octet-stream',
	'.bin' => 'x-binary',
	'.bin' => 'x-macbinary',
	'.bm' => 'image/bmp',
	'.bmp' => 'image/bmp',
	'.bmp' => 'image/x-windows-bmp',
	'.boo' => 'book',
	'.book' => 'book',
	'.boz' => 'x-bzip2',
	'.bsh' => 'x-bsh',
	'.bz' => 'x-bzip',
	'.bz2' => 'x-bzip2',
	'.c' => 'text/plain',
	'.c++' => 'text/plain',
	'.cat' => 'vnd.ms-pki.seccat',
	'.cc' => 'text/plain',
	'.cc' => 'text/x-c',
	'.ccad' => 'clariscad',
	'.cco' => 'x-cocoa',
	'.cdf' => 'cdf',
	'.cdf' => 'x-cdf',
	'.cdf' => 'x-netcdf',
	'.cer' => 'pkix-cert',
	'.cer' => 'x-x509-ca-cert',
	'.cha' => 'x-chat',
	'.chat' => 'x-chat',
	'.class' => 'java',
	'.class' => 'java-byte-code',
	'.class' => 'x-java-class',
	'.com' => 'octet-stream',
	'.com' => 'text/plain',
	'.conf' => 'text/plain',
	'.cpio' => 'x-cpio',
	'.cpp' => 'text/x-c',
	'.cpt' => 'mac-compactpro',
	'.cpt' => 'x-compactpro',
	'.cpt' => 'x-cpt',
	'.crl' => 'pkcs-crl',
	'.crl' => 'pkix-crl',
	'.crt' => 'pkix-cert',
	'.crt' => 'x-x509-ca-cert',
	'.crt' => 'x-x509-user-cert',
	'.csh' => 'x-csh',
	'.csh' => 'text/x-script.csh',
	'.css' => 'x-pointplus',
	'.css' => 'text/css',
	'.cxx' => 'text/plain',
	'.dcr' => 'x-director',
	'.deepv' => 'x-deepv',
	'.def' => 'text/plain',
	'.der' => 'x-x509-ca-cert',
	'.dif' => 'video/x-dv',
	'.dir' => 'x-director',
	'.dl' => 'video/dl',
	'.dl' => 'video/x-dl',
	'.doc' => 'msword',
	'.docx' => 'msword',
	'.dot' => 'msword',
	'.dp' => 'commonground',
	'.drw' => 'drafting',
	'.dump' => 'octet-stream',
	'.dv' => 'video/x-dv',
	'.dvi' => 'x-dvi',
	'.dwf' => 'drawing/x-dwf (old)',
	'.dwf' => 'model/vnd.dwf',
	'.dwg' => 'acad',
	'.dwg' => 'image/vnd.dwg',
	'.dwg' => 'image/x-dwg',
	'.dxf' => 'dxf',
	'.dxf' => 'image/vnd.dwg',
	'.dxf' => 'image/x-dwg',
	'.dxr' => 'x-director',
	'.el' => 'text/x-script.elisp',
	'.elc' => 'x-bytecode.elisp (compiled elisp)',
	'.elc' => 'x-elc',
	'.env' => 'x-envoy',
	'.eps' => 'postscript',
	'.es' => 'x-esrehber',
	'.etx' => 'text/x-setext',
	'.evy' => 'envoy',
	'.evy' => 'x-envoy',
	'.exe' => 'octet-stream',
	'.f' => 'text/plain',
	'.f' => 'text/x-fortran',
	'.f77' => 'text/x-fortran',
	'.f90' => 'text/plain',
	'.f90' => 'text/x-fortran',
	'.fdf' => 'vnd.fdf',
	'.fif' => 'fractals',
	'.fif' => 'image/fif',
	'.fli' => 'video/fli',
	'.fli' => 'video/x-fli',
	'.flo' => 'image/florian',
	'.flx' => 'text/vnd.fmi.flexstor',
	'.fmf' => 'video/x-atomic3d-feature',
	'.for' => 'text/plain',
	'.for' => 'text/x-fortran',
	'.fpx' => 'image/vnd.fpx',
	'.fpx' => 'image/vnd.net-fpx',
	'.frl' => 'freeloader',
	'.funk' => 'audio/make',
	'.g' => 'text/plain',
	'.g3' => 'image/g3fax',
	'.gif' => 'image/gif',
	'.gl' => 'video/gl',
	'.gl' => 'video/x-gl',
	'.gsd' => 'audio/x-gsm',
	'.gsm' => 'audio/x-gsm',
	'.gsp' => 'x-gsp',
	'.gss' => 'x-gss',
	'.gtar' => 'x-gtar',
	'.gz' => 'x-compressed',
	'.gz' => 'x-gzip',
	'.gzip' => 'x-gzip',
	'.gzip' => 'multipart/x-gzip',
	'.h' => 'text/plain',
	'.h' => 'text/x-h',
	'.hdf' => 'x-hdf',
	'.help' => 'x-helpfile',
	'.hgl' => 'vnd.hp-hpgl',
	'.hh' => 'text/plain',
	'.hh' => 'text/x-h',
	'.hlb' => 'text/x-script',
	'.hlp' => 'hlp',
	'.hlp' => 'x-helpfile',
	'.hlp' => 'x-winhelp',
	'.hpg' => 'vnd.hp-hpgl',
	'.hpgl' => 'vnd.hp-hpgl',
	'.hqx' => 'binhex',
	'.hqx' => 'binhex4',
	'.hqx' => 'mac-binhex',
	'.hqx' => 'mac-binhex40',
	'.hqx' => 'x-binhex40',
	'.hqx' => 'x-mac-binhex40',
	'.hta' => 'hta',
	'.htc' => 'text/x-component',
	'.htm' => 'text/html',
	'.html' => 'text/html',
	'.htmls' => 'text/html',
	'.htt' => 'text/webviewhtml',
	'.htx' => 'text/html',
	'.ice' => 'x-conference/x-cooltalk',
	'.ico' => 'image/x-icon',
	'.idc' => 'text/plain',
	'.ief' => 'image/ief',
	'.iefs' => 'image/ief',
	'.iges' => 'iges',
	'.iges' => 'model/iges',
	'.igs' => 'iges',
	'.igs' => 'model/iges',
	'.ima' => 'x-ima',
	'.imap' => 'x-httpd-imap',
	'.inf' => 'inf',
	'.ins' => 'x-internett-signup',
	'.ip' => 'x-ip2',
	'.isu' => 'video/x-isvideo',
	'.it' => 'audio/it',
	'.iv' => 'x-inventor',
	'.ivr' => 'i-world/i-vrml',
	'.ivy' => 'x-livescreen',
	'.jam' => 'audio/x-jam',
	'.jav' => 'text/plain',
	'.jav' => 'text/x-java-source',
	'.java' => 'text/plain',
	'.java' => 'text/x-java-source',
	'.jcm' => 'x-java-commerce',
	'.jfif' => 'image/jpeg',
	'.jfif' => 'image/pjpeg',
	'.jfif-tbnl' => 'image/jpeg',
	'.jpe' => 'imagen jpe',
	'.jpe' => 'imagen jpe',
	'.jpeg' => 'imagen jpeg',
	'.jpeg' => 'imagen jpeg',
	'.jpg' => 'imagen jpeg',
	'.jpg' => 'imagen jpeg',
	'.jps' => 'image/x-jps',
	'.js' => 'x-javascript',
	'.jut' => 'image/jutvision',
	'.kar' => 'audio/midi',
	'.kar' => 'music/x-karaoke',
	'.ksh' => 'x-ksh',
	'.ksh' => 'text/x-script.ksh',
	'.la' => 'audio/nspaudio',
	'.la' => 'audio/x-nspaudio',
	'.lam' => 'audio/x-liveaudio',
	'.latex' => 'x-latex',
	'.lha' => 'lha',
	'.lha' => 'octet-stream',
	'.lha' => 'x-lha',
	'.lhx' => 'octet-stream',
	'.list' => 'text/plain',
	'.lma' => 'audio/nspaudio',
	'.lma' => 'audio/x-nspaudio',
	'.log' => 'text/plain',
	'.lsp' => 'x-lisp',
	'.lsp' => 'text/x-script.lisp',
	'.lst' => 'text/plain',
	'.lsx' => 'text/x-la-asf',
	'.ltx' => 'x-latex',
	'.lzh' => 'octet-stream',
	'.lzh' => 'x-lzh',
	'.lzx' => 'lzx',
	'.lzx' => 'octet-stream',
	'.lzx' => 'x-lzx',
	'.m' => 'text/plain',
	'.m' => 'text/x-m',
	'.m1v' => 'video/mpeg',
	'.m2a' => 'audio/mpeg',
	'.m2v' => 'video/mpeg',
	'.m3u' => 'audio/x-mpequrl',
	'.man' => 'x-troff-man',
	'.map' => 'x-navimap',
	'.mar' => 'text/plain',
	'.mbd' => 'mbedlet',
	'.mc' => 'x-magic-cap-package-1.0',
	'.mcd' => 'mcad',
	'.mcd' => 'x-mathcad',
	'.mcf' => 'image/vasa',
	'.mcf' => 'text/mcf',
	'.mcp' => 'netmc',
	'.me' => 'x-troff-me',
	'.mht' => 'message/rfc822',
	'.mhtml' => 'message/rfc822',
	'.mid' => 'x-midi',
	'.mid' => 'audio/midi',
	'.mid' => 'audio/x-mid',
	'.mid' => 'audio/x-midi',
	'.mid' => 'music/crescendo',
	'.mid' => 'x-music/x-midi',
	'.midi' => 'x-midi',
	'.midi' => 'audio/midi',
	'.midi' => 'audio/x-mid',
	'.midi' => 'audio/x-midi',
	'.midi' => 'music/crescendo',
	'.midi' => 'x-music/x-midi',
	'.mif' => 'x-frame',
	'.mif' => 'x-mif',
	'.mime' => 'message/rfc822',
	'.mime' => 'www/mime',
	'.mjf' => 'audio/x-vnd.audioexplosion.mjuicemediafile',
	'.mjpg' => 'video/x-motion-jpeg',
	'.mm' => 'base64',
	'.mm' => 'x-meme',
	'.mme' => 'base64',
	'.mod' => 'audio/mod',
	'.mod' => 'audio/x-mod',
	'.moov' => 'video/quicktime',
	'.mov' => 'video/quicktime',
	'.movie' => 'video/x-sgi-movie',
	'.mp2' => 'audio/mpeg',
	'.mp2' => 'audio/x-mpeg',
	'.mp2' => 'video/mpeg',
	'.mp2' => 'video/x-mpeg',
	'.mp2' => 'video/x-mpeq2a',
	'.mp3' => 'audio/mpeg3',
	'.mp3' => 'audio/x-mpeg-3',
	'.mp3' => 'video/mpeg',
	'.mp3' => 'video/x-mpeg',
	'.mpa' => 'audio/mpeg',
	'.mpa' => 'video/mpeg',
	'.mpc' => 'x-project',
	'.mpe' => 'video/mpeg',
	'.mpeg' => 'video mpeg',
	'.mpg' => 'audio/mpeg',
	'.mpg' => 'video/mpeg',
	'.mpga' => 'audio/mpeg',
	'.mpp' => 'vnd.ms-project',
	'.mpt' => 'x-project',
	'.mpv' => 'x-project',
	'.mpx' => 'x-project',
	'.mrc' => 'marc',
	'.ms' => 'x-troff-ms',
	'.mv' => 'video/x-sgi-movie',
	'.my' => 'audio/make',
	'.mzz' => 'x-vnd.audioexplosion.mzz',
	'.nap' => 'image/naplps',
	'.naplps' => 'image/naplps',
	'.nc' => 'x-netcdf',
	'.ncm' => 'vnd.nokia.configuration-message',
	'.nif' => 'image/x-niff',
	'.niff' => 'image/x-niff',
	'.nix' => 'x-mix-transfer',
	'.nsc' => 'x-conference',
	'.nvd' => 'x-navidoc',
	'.o' => 'octet-stream',
	'.oda' => 'oda',
	'.omc' => 'x-omc',
	'.omcd' => 'x-omcdatamaker',
	'.omcr' => 'x-omcregerator',
	'.p' => 'text/x-pascal',
	'.p10' => 'pkcs10',
	'.p10' => 'x-pkcs10',
	'.p12' => 'pkcs-12',
	'.p12' => 'x-pkcs12',
	'.p7a' => 'x-pkcs7-signature',
	'.p7c' => 'pkcs7-mime',
	'.p7c' => 'x-pkcs7-mime',
	'.p7m' => 'pkcs7-mime',
	'.p7m' => 'x-pkcs7-mime',
	'.p7r' => 'x-pkcs7-certreqresp',
	'.p7s' => 'pkcs7-signature',
	'.part' => 'pro_eng',
	'.pas' => 'text/pascal',
	'.pbm' => 'image/x-portable-bitmap',
	'.pcl' => 'vnd.hp-pcl',
	'.pcl' => 'x-pcl',
	'.pct' => 'image/x-pict',
	'.pcx' => 'image/x-pcx',
	'.pdb' => 'chemical/x-pdb',
	'.pdf' => 'pdf',
	'.pfunk' => 'audio/make',
	'.pgm' => 'image/x-portable-greymap',
	'.pic' => 'image/pict',
	'.pict' => 'image/pict',
	'.pkg' => 'x-newton-compatible-pkg',
	'.pko' => 'vnd.ms-pki.pko',
	'.pl' => 'text/plain',
	'.pl' => 'text/x-script.perl',
	'.plx' => 'x-pixclscript',
	'.pm' => 'image/x-xpixmap',
	'.pm' => 'text/x-script.perl-module',
	'.pm4' => 'x-pagemaker',
	'.pm5' => 'x-pagemaker',
	'.png' => 'image/png',
	'.pnm' => 'x-portable-anymap',
	'.pnm' => 'image/x-portable-anymap',
	'.pot' => 'mspowerpoint',
	'.pot' => 'vnd.ms-powerpoint',
	'.pov' => 'model/x-pov',
	'.ppa' => 'vnd.ms-powerpoint',
	'.ppm' => 'image/x-portable-pixmap',
	'.pps' => 'mspowerpoint',
	'.pps' => 'vnd.ms-powerpoint',
	'.ppt' => 'mspowerpoint',
	'.ppt' => 'powerpoint',
	'.ppt' => 'vnd.ms-powerpoint',
	'.ppt' => 'x-mspowerpoint',
	'.ppz' => 'mspowerpoint',
	'.pre' => 'x-freelance',
	'.prt' => 'pro_eng',
	'.ps' => 'postscript',
	'.psd' => 'octet-stream',
	'.pvu' => 'paleovu/x-pv',
	'.pwz' => 'vnd.ms-powerpoint',
	'.py' => 'text/x-script.phyton',
	'.pyc' => 'applicaiton/x-bytecode.python',
	'.qcp' => 'audio/vnd.qcelp',
	'.qd3' => 'x-world/x-3dmf',
	'.qd3d' => 'x-world/x-3dmf',
	'.qif' => 'image/x-quicktime',
	'.qt' => 'video/quicktime',
	'.qtc' => 'video/x-qtc',
	'.qti' => 'image/x-quicktime',
	'.qtif' => 'image/x-quicktime',
	'.ra' => 'audio/x-pn-realaudio',
	'.ra' => 'audio/x-pn-realaudio-plugin',
	'.ra' => 'audio/x-realaudio',
	'.ram' => 'audio/x-pn-realaudio',
	'.ras' => 'x-cmu-raster',
	'.ras' => 'image/cmu-raster',
	'.ras' => 'image/x-cmu-raster',
	'.rast' => 'image/cmu-raster',
	'.rexx' => 'text/x-script.rexx',
	'.rf' => 'image/vnd.rn-realflash',
	'.rgb' => 'image/x-rgb',
	'.rm' => 'vnd.rn-realmedia',
	'.rm' => 'audio/x-pn-realaudio',
	'.rmi' => 'audio/mid',
	'.rmm' => 'audio/x-pn-realaudio',
	'.rmp' => 'audio/x-pn-realaudio',
	'.rmp' => 'audio/x-pn-realaudio-plugin',
	'.rng' => 'ringing-tones',
	'.rng' => 'vnd.nokia.ringing-tone',
	'.rnx' => 'vnd.rn-realplayer',
	'.roff' => 'x-troff',
	'.rp' => 'image/vnd.rn-realpix',
	'.rpm' => 'audio/x-pn-realaudio-plugin',
	'.rt' => 'text/richtext',
	'.rt' => 'text/vnd.rn-realtext',
	'.rtf' => 'rtf',
	'.rtf' => 'x-rtf',
	'.rtf' => 'text/richtext',
	'.rtx' => 'rtf',
	'.rtx' => 'text/richtext',
	'.rv' => 'video/vnd.rn-realvideo',
	'.s' => 'text/x-asm',
	'.s3m' => 'audio/s3m',
	'.saveme' => 'aoctet-stream',
	'.sbk' => 'x-tbook',
	'.scm' => 'x-lotusscreencam',
	'.scm' => 'text/x-script.guile',
	'.scm' => 'text/x-script.scheme',
	'.scm' => 'video/x-scm',
	'.sdml' => 'text/plain',
	'.sdp' => 'sdp',
	'.sdp' => 'x-sdp',
	'.sdr' => 'sounder',
	'.sea' => 'sea',
	'.sea' => 'x-sea',
	'.set' => 'set',
	'.sgm' => 'text/sgml',
	'.sgm' => 'text/x-sgml',
	'.sgml' => 'text/sgml',
	'.sgml' => 'text/x-sgml',
	'.sh' => 'x-bsh',
	'.sh' => 'x-sh',
	'.sh' => 'x-shar',
	'.sh' => 'text/x-script.sh',
	'.shar' => 'x-bsh',
	'.shar' => 'x-shar',
	'.shtml' => 'text/html',
	'.shtml' => 'text/x-server-parsed-html',
	'.sid' => 'audio/x-psid',
	'.sit' => 'x-sit',
	'.sit' => 'x-stuffit',
	'.skd' => 'x-koan',
	'.skm' => 'x-koan',
	'.skp' => 'x-koan',
	'.skt' => 'x-koan',
	'.sl' => 'x-seelogo',
	'.smi' => 'smil',
	'.smil' => 'smil',
	'.snd' => 'audio/basic',
	'.snd' => 'audio/x-adpcm',
	'.sol' => 'solids',
	'.spc' => 'x-pkcs7-certificates',
	'.spc' => 'text/x-speech',
	'.spl' => 'futuresplash',
	'.spr' => 'x-sprite',
	'.sprite' => 'x-sprite',
	'.src' => 'x-wais-source',
	'.ssi' => 'text/x-server-parsed-html',
	'.ssm' => 'streamingmedia',
	'.sst' => 'vnd.ms-pki.certstore',
	'.step' => 'step',
	'.stl' => 'sla',
	'.stl' => 'vnd.ms-pki.stl',
	'.stl' => 'x-navistyle',
	'.stp' => 'step',
	'.sv4cpio' =>'x-sv4cpio',
	'.sv4crc' => 'x-sv4crc',
	'.svf' => 'image/vnd.dwg',
	'.svf' => 'image/x-dwg',
	'.svr' => 'x-world',
	'.svr' => 'x-world/x-svr',
	'.swf' => 'x-shockwave-flash',
	'.t' => 'x-troff',
	'.talk' => 'text/x-speech',
	'.tar' => 'x-tar',
	'.tbk' => 'toolbook',
	'.tbk' => 'x-tbook',
	'.tcl' => 'x-tcl',
	'.tcl' => 'text/x-script.tcl',
	'.tcsh' => 'text/x-script.tcsh',
	'.tex' => 'x-tex',
	'.texi' => 'x-texinfo',
	'.texinfo' =>' lication/x-texinfo',
	'.text' => 'plain',
	'.text' => 'text/plain',
	'.tgz' => 'gnutar',
	'.tgz' => 'x-compressed',
	'.tif' => 'image/tiff',
	'.tif' => 'image/x-tiff',
	'.tiff' => 'image/tiff',
	'.tiff' => 'image/x-tiff',
	'.tr' => 'x-troff',
	'.tsi' => 'audio/tsp-audio',
	'.tsp' => 'dsptype',
	'.tsp' => 'audio/tsplayer',
	'.tsv' => 'text/tab-separated-values',
	'.turbot' => 'image/florian',
	'.txt' => 'text/plain',
	'.uil' => 'text/x-uil',
	'.uni' => 'text/uri-list',
	'.unis' => 'text/uri-list',
	'.unv' => 'i-deas',
	'.uri' => 'text/uri-list',
	'.uris' => 'text/uri-list',
	'.ustar' => 'x-ustar',
	'.ustar' => 'multipart/x-ustar',
	'.uu' => 'octet-stream',
	'.uu' => 'text/x-uuencode',
	'.uue' => 'text/x-uuencode',
	'.vcd' => 'x-cdlink',
	'.vcs' => 'text/x-vcalendar',
	'.vda' => 'vda',
	'.vdo' => 'video/vdo',
	'.vew' => 'groupwise',
	'.viv' => 'video/vivo',
	'.viv' => 'video/vnd.vivo',
	'.vivo' => 'video/vivo',
	'.vivo' => 'video/vnd.vivo',
	'.vmd' => 'vocaltec-media-desc',
	'.vmf' => 'vocaltec-media-file',
	'.voc' => 'audio/voc',
	'.voc' => 'audio/x-voc',
	'.vos' => 'video/vosaic',
	'.vox' => 'audio/voxware',
	'.vqe' => 'audio/x-twinvq-plugin',
	'.vqf' => 'audio/x-twinvq',
	'.vql' => 'audio/x-twinvq-plugin',
	'.vrml' => 'x-vrml',
	'.vrml' => 'model/vrml',
	'.vrml' => 'x-world/x-vrml',
	'.vrt' => 'x-world/x-vrt',
	'.vsd' => 'x-visio',
	'.vst' => 'x-visio',
	'.vsw' => 'x-visio',
	'.w60' => 'wordperfect6.0',
	'.w61' => 'wordperfect6.1',
	'.w6w' => 'msword',
	'.wav' => 'audio/wav',
	'.wav' => 'audio/x-wav',
	'.wb1' => 'x-qpro',
	'.wbmp' => 'image/vnd.wap.wbmp',
	'.web' => 'vnd.xara',
	'.wiz' => 'msword',
	'.wk1' => 'x-123',
	'.wmf' => 'windows/metafile',
	'.wml' => 'text/vnd.wap.wml',
	'.wmlc' => 'vnd.wap.wmlc',
	'.wmls' => 'text/vnd.wap.wmlscript',
	'.wmlsc' => 'vnd.wap.wmlscriptc',
	'.word' => 'msword',
	'.wp' => 'wordperfect',
	'.wp5' => 'wordperfect',
	'.wp5' => 'wordperfect6.0',
	'.wp6' => 'wordperfect',
	'.wpd' => 'wordperfect',
	'.wpd' => 'x-wpwin',
	'.wq1' => 'x-lotus',
	'.wri' => 'mswrite',
	'.wri' => 'x-wri',
	'.wrl' => 'x-world',
	'.wrl' => 'model/vrml',
	'.wrl' => 'x-world/x-vrml',
	'.wrz' => 'model/vrml',
	'.wrz' => 'x-world/x-vrml',
	'.wsc' => 'text/scriplet',
	'.wsrc' => 'x-wais-source',
	'.wtk' => 'x-wintalk',
	'.xbm' => 'image/x-xbitmap',
	'.xbm' => 'image/x-xbm',
	'.xbm' => 'image/xbm',
	'.xdr' => 'video/x-amt-demorun',
	'.xgz' => 'xgl/drawing',
	'.xif' => 'image/vnd.xiff',
	'.xl' => 'excel',
	'.xla' => 'excel',
	'.xla' => 'x-excel',
	'.xla' => 'excel',
	'.xlb' => 'excel',
	'.xlb' => 'vnd.ms-excel',
	'.xlb' => 'x-excel',
	'.xlc' => 'excel',
	'.xlc' => 'vnd.ms-excel',
	'.xlc' => 'x-excel',
	'.xld' => 'excel',
	'.xld' => 'x-excel',
	'.xlk' => 'excel',
	'.xlk' => 'x-excel',
	'.xll' => 'excel',
	'.xll' => 'vnd.ms-excel',
	'.xll' => 'x-excel',
	'.xlm' => 'excel',
	'.xlm' => 'vnd.ms-excel',
	'.xlm' => 'x-excel',
	'.xls' => 'excel',
	'.xls' => 'vnd.ms-excel',
	'.xls' => 'excel',
	'.xls' => 'excel',
	'.xlt' => 'excel',
	'.xlt' => 'x-excel',
	'.xlv' => 'excel',
	'.xlv' => 'x-excel',
	'.xlw' => 'excel',
	'.xlw' => 'vnd.ms-excel',
	'.xlw' => 'x-excel',
	'.xlw' => 'x-msexcel',
	'.xm' => 'audio/xm',
	'.xml' => 'xml',
	'.xml' => 'text/xml',
	'.xmz' => 'xgl/movie',
	'.xpix' => 'x-vnd.ls-xpix',
	'.xpm' => 'image/x-xpixmap',
	'.xpm' => 'image/xpm',
	'.x-png' => 'image/png',
	'.xsr' => 'video/x-amt-showrun',
	'.xwd' => 'image/x-xwd',
	'.xwd' => 'image/x-xwindowdump',
	'.xyz' => 'chemical/x-pdb',
	'.z' => 'archivo comprimido',
	'.z' => 'archivo comprimido',
	'.zip' => 'archivo zip',
	'.zip' => 'archivo zip',
	'.zip' => 'archivo zip',
	'.zip' => 'archivo zip',
	'.zoo' => 'octet-stream',
	'.zsh' => 'text/x-script.zsh)'
);
*/



$mime_types = array(
	'.3dm' => 'x-world/x-3dmf',
	'.3dmf' => 'x-world/x-3dmf',
	'.a' => 'octet-stream',
	'.aab' => 'x-authorware-bin',
	'.aam' => 'x-authorware-map',
	'.aas' => 'x-authorware-seg',
	'.abc' => 'text/vnd.abc',
	'.acgi' => 'text/html',
	'.afl' => 'video/animaflex',
	'.ai' => 'postscript',
	'.aif' => 'audio/aiff',
	'.aif' => 'audio/x-aiff',
	'.aifc' => 'audio/aiff',
	'.aifc' => 'audio/x-aiff',
	'.aiff' => 'audio/aiff',
	'.aiff' => 'audio/x-aiff',
	'.aim' => 'x-aim',
	'.aip' => 'text/x-audiosoft-intra',
	'.ani' => 'x-navi-animation',
	'.aos' => 'x-nokia-9000-communicator-add-on-software',
	'.aps' => 'mime',
	'.arc' => 'octet-stream',
	'.arj' => 'arj',
	'.arj' => 'octet-stream',
	'.art' => 'image/x-jg',
	'.asf' => 'video/x-ms-asf',
	'.asm' => 'text/x-asm',
	'.asp' => 'text/asp',
	'.asx' => 'x-mplayer2',
	'.asx' => 'video/x-ms-asf',
	'.asx' => 'video/x-ms-asf-plugin',
	'.au' => 'audio/basic',
	'.au' => 'audio/x-au',
	'.avi' => 'x-troff-msvideo',
	'.avi' => 'video/avi',
	'.avi' => 'video/msvideo',
	'.avi' => 'video/x-msvideo',
	'.avs' => 'video/avs-video',
	'.bcpio' => 'x-bcpio',
	'.bin' => 'mac-binary',
	'.bin' => 'macbinary',
	'.bin' => 'octet-stream',
	'.bin' => 'x-binary',
	'.bin' => 'x-macbinary',
	'.bm' => 'image/bmp',
	'.bmp' => 'image/bmp',
	'.bmp' => 'image/x-windows-bmp',
	'.boo' => 'book',
	'.book' => 'book',
	'.boz' => 'x-bzip2',
	'.bsh' => 'x-bsh',
	'.bz' => 'x-bzip',
	'.bz2' => 'x-bzip2',
	'.c' => 'text/plain',
	'.c++' => 'text/plain',
	'.cat' => 'vnd.ms-pki.seccat',
	'.cc' => 'text/plain',
	'.cc' => 'text/x-c',
	'.ccad' => 'clariscad',
	'.cco' => 'x-cocoa',
	'.cdf' => 'cdf',
	'.cdf' => 'x-cdf',
	'.cdf' => 'x-netcdf',
	'.cer' => 'pkix-cert',
	'.cer' => 'x-x509-ca-cert',
	'.cha' => 'x-chat',
	'.chat' => 'x-chat',
	'.class' => 'java',
	'.class' => 'java-byte-code',
	'.class' => 'x-java-class',
	'.com' => 'octet-stream',
	'.com' => 'text/plain',
	'.conf' => 'text/plain',
	'.cpio' => 'x-cpio',
	'.cpp' => 'text/x-c',
	'.cpt' => 'mac-compactpro',
	'.cpt' => 'x-compactpro',
	'.cpt' => 'x-cpt',
	'.crl' => 'pkcs-crl',
	'.crl' => 'pkix-crl',
	'.crt' => 'pkix-cert',
	'.crt' => 'x-x509-ca-cert',
	'.crt' => 'x-x509-user-cert',
	'.csh' => 'x-csh',
	'.csh' => 'text/x-script.csh',
	'.css' => 'x-pointplus',
	'.css' => 'text/css',
	'.cxx' => 'text/plain',
	'.dcr' => 'x-director',
	'.deepv' => 'x-deepv',
	'.def' => 'text/plain',
	'.der' => 'x-x509-ca-cert',
	'.dif' => 'video/x-dv',
	'.dir' => 'x-director',
	'.dl' => 'video/dl',
	'.dl' => 'video/x-dl',
	'.doc' => 'msword',
	'.docx' => 'msword',
	'.dot' => 'msword',
	'.dp' => 'commonground',
	'.drw' => 'drafting',
	'.dump' => 'octet-stream',
	'.dv' => 'video/x-dv',
	'.dvi' => 'x-dvi',
	'.dwf' => 'drawing/x-dwf (old)',
	'.dwf' => 'model/vnd.dwf',
	'.dwg' => 'acad',
	'.dwg' => 'image/vnd.dwg',
	'.dwg' => 'image/x-dwg',
	'.dxf' => 'dxf',
	'.dxf' => 'image/vnd.dwg',
	'.dxf' => 'image/x-dwg',
	'.dxr' => 'x-director',
	'.el' => 'text/x-script.elisp',
	'.elc' => 'x-bytecode.elisp (compiled elisp)',
	'.elc' => 'x-elc',
	'.env' => 'x-envoy',
	'.eps' => 'postscript',
	'.es' => 'x-esrehber',
	'.etx' => 'text/x-setext',
	'.evy' => 'envoy',
	'.evy' => 'x-envoy',
	'.exe' => 'octet-stream',
	'.f' => 'text/plain',
	'.f' => 'text/x-fortran',
	'.f77' => 'text/x-fortran',
	'.f90' => 'text/plain',
	'.f90' => 'text/x-fortran',
	'.fdf' => 'vnd.fdf',
	'.fif' => 'fractals',
	'.fif' => 'image/fif',
	'.fli' => 'video/fli',
	'.fli' => 'video/x-fli',
	'.flo' => 'image/florian',
	'.flx' => 'text/vnd.fmi.flexstor',
	'.fmf' => 'video/x-atomic3d-feature',
	'.for' => 'text/plain',
	'.for' => 'text/x-fortran',
	'.fpx' => 'image/vnd.fpx',
	'.fpx' => 'image/vnd.net-fpx',
	'.frl' => 'freeloader',
	'.funk' => 'audio/make',
	'.g' => 'text/plain',
	'.g3' => 'image/g3fax',
	'.gif' => 'image/gif',
	'.gl' => 'video/gl',
	'.gl' => 'video/x-gl',
	'.gsd' => 'audio/x-gsm',
	'.gsm' => 'audio/x-gsm',
	'.gsp' => 'x-gsp',
	'.gss' => 'x-gss',
	'.gtar' => 'x-gtar',
	'.gz' => 'x-compressed',
	'.gz' => 'x-gzip',
	'.gzip' => 'x-gzip',
	'.gzip' => 'multipart/x-gzip',
	'.h' => 'text/plain',
	'.h' => 'text/x-h',
	'.hdf' => 'x-hdf',
	'.help' => 'x-helpfile',
	'.hgl' => 'vnd.hp-hpgl',
	'.hh' => 'text/plain',
	'.hh' => 'text/x-h',
	'.hlb' => 'text/x-script',
	'.hlp' => 'hlp',
	'.hlp' => 'x-helpfile',
	'.hlp' => 'x-winhelp',
	'.hpg' => 'vnd.hp-hpgl',
	'.hpgl' => 'vnd.hp-hpgl',
	'.hqx' => 'binhex',
	'.hqx' => 'binhex4',
	'.hqx' => 'mac-binhex',
	'.hqx' => 'mac-binhex40',
	'.hqx' => 'x-binhex40',
	'.hqx' => 'x-mac-binhex40',
	'.hta' => 'hta',
	'.htc' => 'text/x-component',
	'.htm' => 'text/html',
	'.html' => 'text/html',
	'.htmls' => 'text/html',
	'.htt' => 'text/webviewhtml',
	'.htx' => 'text/html',
	'.ice' => 'x-conference/x-cooltalk',
	'.ico' => 'image/x-icon',
	'.idc' => 'text/plain',
	'.ief' => 'image/ief',
	'.iefs' => 'image/ief',
	'.iges' => 'iges',
	'.iges' => 'model/iges',
	'.igs' => 'iges',
	'.igs' => 'model/iges',
	'.ima' => 'x-ima',
	'.imap' => 'x-httpd-imap',
	'.inf' => 'inf',
	'.ins' => 'x-internett-signup',
	'.ip' => 'x-ip2',
	'.isu' => 'video/x-isvideo',
	'.it' => 'audio/it',
	'.iv' => 'x-inventor',
	'.ivr' => 'i-world/i-vrml',
	'.ivy' => 'x-livescreen',
	'.jam' => 'audio/x-jam',
	'.jav' => 'text/plain',
	'.jav' => 'text/x-java-source',
	'.java' => 'text/plain',
	'.java' => 'text/x-java-source',
	'.jcm' => 'x-java-commerce',
	'.jfif' => 'image/jpeg',
	'.jfif' => 'image/pjpeg',
	'.jfif-tbnl' => 'image/jpeg',
	'.jpe' => 'image/jpeg',
	'.jpe' => 'image/jpeg',
	'.jpeg' => 'image/jpeg',
	'.jpeg' => 'image/jpeg',
	'.jpg' => 'image/jpeg',
	'.jpg' => 'image/jpeg',
	'.jps' => 'image/x-jps',
	'.js' => 'x-javascript',
	'.jut' => 'image/jutvision',
	'.kar' => 'audio/midi',
	'.kar' => 'music/x-karaoke',
	'.ksh' => 'x-ksh',
	'.ksh' => 'text/x-script.ksh',
	'.la' => 'audio/nspaudio',
	'.la' => 'audio/x-nspaudio',
	'.lam' => 'audio/x-liveaudio',
	'.latex' => 'x-latex',
	'.lha' => 'lha',
	'.lha' => 'octet-stream',
	'.lha' => 'x-lha',
	'.lhx' => 'octet-stream',
	'.list' => 'text/plain',
	'.lma' => 'audio/nspaudio',
	'.lma' => 'audio/x-nspaudio',
	'.log' => 'text/plain',
	'.lsp' => 'x-lisp',
	'.lsp' => 'text/x-script.lisp',
	'.lst' => 'text/plain',
	'.lsx' => 'text/x-la-asf',
	'.ltx' => 'x-latex',
	'.lzh' => 'octet-stream',
	'.lzh' => 'x-lzh',
	'.lzx' => 'lzx',
	'.lzx' => 'octet-stream',
	'.lzx' => 'x-lzx',
	'.m' => 'text/plain',
	'.m' => 'text/x-m',
	'.m1v' => 'video/mpeg',
	'.m2a' => 'audio/mpeg',
	'.m2v' => 'video/mpeg',
	'.m3u' => 'audio/x-mpequrl',
	'.man' => 'x-troff-man',
	'.map' => 'x-navimap',
	'.mar' => 'text/plain',
	'.mbd' => 'mbedlet',
	'.mc' => 'x-magic-cap-package-1.0',
	'.mcd' => 'mcad',
	'.mcd' => 'x-mathcad',
	'.mcf' => 'image/vasa',
	'.mcf' => 'text/mcf',
	'.mcp' => 'netmc',
	'.me' => 'x-troff-me',
	'.mht' => 'message/rfc822',
	'.mhtml' => 'message/rfc822',
	'.mid' => 'x-midi',
	'.mid' => 'audio/midi',
	'.mid' => 'audio/x-mid',
	'.mid' => 'audio/x-midi',
	'.mid' => 'music/crescendo',
	'.mid' => 'x-music/x-midi',
	'.midi' => 'x-midi',
	'.midi' => 'audio/midi',
	'.midi' => 'audio/x-mid',
	'.midi' => 'audio/x-midi',
	'.midi' => 'music/crescendo',
	'.midi' => 'x-music/x-midi',
	'.mif' => 'x-frame',
	'.mif' => 'x-mif',
	'.mime' => 'message/rfc822',
	'.mime' => 'www/mime',
	'.mjf' => 'audio/x-vnd.audioexplosion.mjuicemediafile',
	'.mjpg' => 'video/x-motion-jpeg',
	'.mm' => 'base64',
	'.mm' => 'x-meme',
	'.mme' => 'base64',
	'.mod' => 'audio/mod',
	'.mod' => 'audio/x-mod',
	'.moov' => 'video/quicktime',
	'.mov' => 'video/quicktime',
	'.movie' => 'video/x-sgi-movie',
	'.mp2' => 'audio/mpeg',
	'.mp2' => 'audio/x-mpeg',
	'.mp2' => 'video/mpeg',
	'.mp2' => 'video/x-mpeg',
	'.mp2' => 'video/x-mpeq2a',
	'.mp3' => 'audio/mpeg3',
	'.mp3' => 'audio/x-mpeg-3',
	'.mp3' => 'video/mpeg',
	'.mp3' => 'video/x-mpeg',
	'.mpa' => 'audio/mpeg',
	'.mpa' => 'video/mpeg',
	'.mpc' => 'x-project',
	'.mpe' => 'video/mpeg',
	'.mpeg' => 'video/mpeg',
	'.mpg' => 'audio/mpeg',
	'.mpg' => 'video/mpeg',
	'.mpga' => 'audio/mpeg',
	'.mpp' => 'vnd.ms-project',
	'.mpt' => 'x-project',
	'.mpv' => 'x-project',
	'.mpx' => 'x-project',
	'.mrc' => 'marc',
	'.ms' => 'x-troff-ms',
	'.mv' => 'video/x-sgi-movie',
	'.my' => 'audio/make',
	'.mzz' => 'x-vnd.audioexplosion.mzz',
	'.nap' => 'image/naplps',
	'.naplps' => 'image/naplps',
	'.nc' => 'x-netcdf',
	'.ncm' => 'vnd.nokia.configuration-message',
	'.nif' => 'image/x-niff',
	'.niff' => 'image/x-niff',
	'.nix' => 'x-mix-transfer',
	'.nsc' => 'x-conference',
	'.nvd' => 'x-navidoc',
	'.o' => 'octet-stream',
	'.oda' => 'oda',
	'.omc' => 'x-omc',
	'.omcd' => 'x-omcdatamaker',
	'.omcr' => 'x-omcregerator',
	'.p' => 'text/x-pascal',
	'.p10' => 'pkcs10',
	'.p10' => 'x-pkcs10',
	'.p12' => 'pkcs-12',
	'.p12' => 'x-pkcs12',
	'.p7a' => 'x-pkcs7-signature',
	'.p7c' => 'pkcs7-mime',
	'.p7c' => 'x-pkcs7-mime',
	'.p7m' => 'pkcs7-mime',
	'.p7m' => 'x-pkcs7-mime',
	'.p7r' => 'x-pkcs7-certreqresp',
	'.p7s' => 'pkcs7-signature',
	'.part' => 'pro_eng',
	'.pas' => 'text/pascal',
	'.pbm' => 'image/x-portable-bitmap',
	'.pcl' => 'vnd.hp-pcl',
	'.pcl' => 'x-pcl',
	'.pct' => 'image/x-pict',
	'.pcx' => 'image/x-pcx',
	'.pdb' => 'chemical/x-pdb',
	'.pdf' => 'pdf',
	'.pfunk' => 'audio/make',
	'.pgm' => 'image/x-portable-greymap',
	'.pic' => 'image/pict',
	'.pict' => 'image/pict',
	'.pkg' => 'x-newton-compatible-pkg',
	'.pko' => 'vnd.ms-pki.pko',
	'.pl' => 'text/plain',
	'.pl' => 'text/x-script.perl',
	'.plx' => 'x-pixclscript',
	'.pm' => 'image/x-xpixmap',
	'.pm' => 'text/x-script.perl-module',
	'.pm4' => 'x-pagemaker',
	'.pm5' => 'x-pagemaker',
	'.png' => 'image/png',
	'.pnm' => 'x-portable-anymap',
	'.pnm' => 'image/x-portable-anymap',
	'.pot' => 'mspowerpoint',
	'.pot' => 'vnd.ms-powerpoint',
	'.pov' => 'model/x-pov',
	'.ppa' => 'vnd.ms-powerpoint',
	'.ppm' => 'image/x-portable-pixmap',
	'.pps' => 'mspowerpoint',
	'.pps' => 'vnd.ms-powerpoint',
	'.ppt' => 'mspowerpoint',
	'.ppt' => 'powerpoint',
	'.ppt' => 'vnd.ms-powerpoint',
	'.ppt' => 'x-mspowerpoint',
	'.ppz' => 'mspowerpoint',
	'.pre' => 'x-freelance',
	'.prt' => 'pro_eng',
	'.ps' => 'postscript',
	'.psd' => 'octet-stream',
	'.pvu' => 'paleovu/x-pv',
	'.pwz' => 'vnd.ms-powerpoint',
	'.py' => 'text/x-script.phyton',
	'.pyc' => 'applicaiton/x-bytecode.python',
	'.qcp' => 'audio/vnd.qcelp',
	'.qd3' => 'x-world/x-3dmf',
	'.qd3d' => 'x-world/x-3dmf',
	'.qif' => 'image/x-quicktime',
	'.qt' => 'video/quicktime',
	'.qtc' => 'video/x-qtc',
	'.qti' => 'image/x-quicktime',
	'.qtif' => 'image/x-quicktime',
	'.ra' => 'audio/x-pn-realaudio',
	'.ra' => 'audio/x-pn-realaudio-plugin',
	'.ra' => 'audio/x-realaudio',
	'.ram' => 'audio/x-pn-realaudio',
	'.ras' => 'x-cmu-raster',
	'.ras' => 'image/cmu-raster',
	'.ras' => 'image/x-cmu-raster',
	'.rast' => 'image/cmu-raster',
	'.rexx' => 'text/x-script.rexx',
	'.rf' => 'image/vnd.rn-realflash',
	'.rgb' => 'image/x-rgb',
	'.rm' => 'vnd.rn-realmedia',
	'.rm' => 'audio/x-pn-realaudio',
	'.rmi' => 'audio/mid',
	'.rmm' => 'audio/x-pn-realaudio',
	'.rmp' => 'audio/x-pn-realaudio',
	'.rmp' => 'audio/x-pn-realaudio-plugin',
	'.rng' => 'ringing-tones',
	'.rng' => 'vnd.nokia.ringing-tone',
	'.rnx' => 'vnd.rn-realplayer',
	'.roff' => 'x-troff',
	'.rp' => 'image/vnd.rn-realpix',
	'.rpm' => 'audio/x-pn-realaudio-plugin',
	'.rt' => 'text/richtext',
	'.rt' => 'text/vnd.rn-realtext',
	'.rtf' => 'rtf',
	'.rtf' => 'x-rtf',
	'.rtf' => 'text/richtext',
	'.rtx' => 'rtf',
	'.rtx' => 'text/richtext',
	'.rv' => 'video/vnd.rn-realvideo',
	'.s' => 'text/x-asm',
	'.s3m' => 'audio/s3m',
	'.saveme' => 'aoctet-stream',
	'.sbk' => 'x-tbook',
	'.scm' => 'x-lotusscreencam',
	'.scm' => 'text/x-script.guile',
	'.scm' => 'text/x-script.scheme',
	'.scm' => 'video/x-scm',
	'.sdml' => 'text/plain',
	'.sdp' => 'sdp',
	'.sdp' => 'x-sdp',
	'.sdr' => 'sounder',
	'.sea' => 'sea',
	'.sea' => 'x-sea',
	'.set' => 'set',
	'.sgm' => 'text/sgml',
	'.sgm' => 'text/x-sgml',
	'.sgml' => 'text/sgml',
	'.sgml' => 'text/x-sgml',
	'.sh' => 'x-bsh',
	'.sh' => 'x-sh',
	'.sh' => 'x-shar',
	'.sh' => 'text/x-script.sh',
	'.shar' => 'x-bsh',
	'.shar' => 'x-shar',
	'.shtml' => 'text/html',
	'.shtml' => 'text/x-server-parsed-html',
	'.sid' => 'audio/x-psid',
	'.sit' => 'x-sit',
	'.sit' => 'x-stuffit',
	'.skd' => 'x-koan',
	'.skm' => 'x-koan',
	'.skp' => 'x-koan',
	'.skt' => 'x-koan',
	'.sl' => 'x-seelogo',
	'.smi' => 'smil',
	'.smil' => 'smil',
	'.snd' => 'audio/basic',
	'.snd' => 'audio/x-adpcm',
	'.sol' => 'solids',
	'.spc' => 'x-pkcs7-certificates',
	'.spc' => 'text/x-speech',
	'.spl' => 'futuresplash',
	'.spr' => 'x-sprite',
	'.sprite' => 'x-sprite',
	'.src' => 'x-wais-source',
	'.ssi' => 'text/x-server-parsed-html',
	'.ssm' => 'streamingmedia',
	'.sst' => 'vnd.ms-pki.certstore',
	'.step' => 'step',
	'.stl' => 'sla',
	'.stl' => 'vnd.ms-pki.stl',
	'.stl' => 'x-navistyle',
	'.stp' => 'step',
	'.sv4cpio' =>'x-sv4cpio',
	'.sv4crc' => 'x-sv4crc',
	'.svf' => 'image/vnd.dwg',
	'.svf' => 'image/x-dwg',
	'.svr' => 'x-world',
	'.svr' => 'x-world/x-svr',
	'.swf' => 'x-shockwave-flash',
	'.t' => 'x-troff',
	'.talk' => 'text/x-speech',
	'.tar' => 'x-tar',
	'.tbk' => 'toolbook',
	'.tbk' => 'x-tbook',
	'.tcl' => 'x-tcl',
	'.tcl' => 'text/x-script.tcl',
	'.tcsh' => 'text/x-script.tcsh',
	'.tex' => 'x-tex',
	'.texi' => 'x-texinfo',
	'.texinfo' =>' lication/x-texinfo',
	'.text' => 'plain',
	'.text' => 'text/plain',
	'.tgz' => 'gnutar',
	'.tgz' => 'x-compressed',
	'.tif' => 'image/tiff',
	'.tif' => 'image/x-tiff',
	'.tiff' => 'image/tiff',
	'.tiff' => 'image/x-tiff',
	'.tr' => 'x-troff',
	'.tsi' => 'audio/tsp-audio',
	'.tsp' => 'dsptype',
	'.tsp' => 'audio/tsplayer',
	'.tsv' => 'text/tab-separated-values',
	'.turbot' => 'image/florian',
	'.txt' => 'text/plain',
	'.uil' => 'text/x-uil',
	'.uni' => 'text/uri-list',
	'.unis' => 'text/uri-list',
	'.unv' => 'i-deas',
	'.uri' => 'text/uri-list',
	'.uris' => 'text/uri-list',
	'.ustar' => 'x-ustar',
	'.ustar' => 'multipart/x-ustar',
	'.uu' => 'octet-stream',
	'.uu' => 'text/x-uuencode',
	'.uue' => 'text/x-uuencode',
	'.vcd' => 'x-cdlink',
	'.vcs' => 'text/x-vcalendar',
	'.vda' => 'vda',
	'.vdo' => 'video/vdo',
	'.vew' => 'groupwise',
	'.viv' => 'video/vivo',
	'.viv' => 'video/vnd.vivo',
	'.vivo' => 'video/vivo',
	'.vivo' => 'video/vnd.vivo',
	'.vmd' => 'vocaltec-media-desc',
	'.vmf' => 'vocaltec-media-file',
	'.voc' => 'audio/voc',
	'.voc' => 'audio/x-voc',
	'.vos' => 'video/vosaic',
	'.vox' => 'audio/voxware',
	'.vqe' => 'audio/x-twinvq-plugin',
	'.vqf' => 'audio/x-twinvq',
	'.vql' => 'audio/x-twinvq-plugin',
	'.vrml' => 'x-vrml',
	'.vrml' => 'model/vrml',
	'.vrml' => 'x-world/x-vrml',
	'.vrt' => 'x-world/x-vrt',
	'.vsd' => 'x-visio',
	'.vst' => 'x-visio',
	'.vsw' => 'x-visio',
	'.w60' => 'wordperfect6.0',
	'.w61' => 'wordperfect6.1',
	'.w6w' => 'msword',
	'.wav' => 'audio/wav',
	'.wav' => 'audio/x-wav',
	'.wb1' => 'x-qpro',
	'.wbmp' => 'image/vnd.wap.wbmp',
	'.web' => 'vnd.xara',
	'.wiz' => 'msword',
	'.wk1' => 'x-123',
	'.wmf' => 'windows/metafile',
	'.wml' => 'text/vnd.wap.wml',
	'.wmlc' => 'vnd.wap.wmlc',
	'.wmls' => 'text/vnd.wap.wmlscript',
	'.wmlsc' => 'vnd.wap.wmlscriptc',
	'.word' => 'msword',
	'.wp' => 'wordperfect',
	'.wp5' => 'wordperfect',
	'.wp5' => 'wordperfect6.0',
	'.wp6' => 'wordperfect',
	'.wpd' => 'wordperfect',
	'.wpd' => 'x-wpwin',
	'.wq1' => 'x-lotus',
	'.wri' => 'mswrite',
	'.wri' => 'x-wri',
	'.wrl' => 'x-world',
	'.wrl' => 'model/vrml',
	'.wrl' => 'x-world/x-vrml',
	'.wrz' => 'model/vrml',
	'.wrz' => 'x-world/x-vrml',
	'.wsc' => 'text/scriplet',
	'.wsrc' => 'x-wais-source',
	'.wtk' => 'x-wintalk',
	'.xbm' => 'image/x-xbitmap',
	'.xbm' => 'image/x-xbm',
	'.xbm' => 'image/xbm',
	'.xdr' => 'video/x-amt-demorun',
	'.xgz' => 'xgl/drawing',
	'.xif' => 'image/vnd.xiff',
	'.xl' => 'excel',
	'.xla' => 'excel',
	'.xla' => 'x-excel',
	'.xla' => 'x-msexcel',
	'.xlb' => 'excel',
	'.xlb' => 'vnd.ms-excel',
	'.xlb' => 'x-excel',
	'.xlc' => 'excel',
	'.xlc' => 'vnd.ms-excel',
	'.xlc' => 'x-excel',
	'.xld' => 'excel',
	'.xld' => 'x-excel',
	'.xlk' => 'excel',
	'.xlk' => 'x-excel',
	'.xll' => 'excel',
	'.xll' => 'vnd.ms-excel',
	'.xll' => 'x-excel',
	'.xlm' => 'excel',
	'.xlm' => 'vnd.ms-excel',
	'.xlm' => 'x-excel',
	'.xls' => 'excel',
	'.xls' => 'vnd.ms-excel',
	'.xls' => 'x-excel',
	'.xls' => 'x-msexcel',
	'.xlt' => 'excel',
	'.xlt' => 'x-excel',
	'.xlv' => 'excel',
	'.xlv' => 'x-excel',
	'.xlw' => 'excel',
	'.xlw' => 'vnd.ms-excel',
	'.xlw' => 'x-excel',
	'.xlw' => 'x-msexcel',
	'.xm' => 'audio/xm',
	'.xml' => 'xml',
	'.xml' => 'text/xml',
	'.xmz' => 'xgl/movie',
	'.xpix' => 'x-vnd.ls-xpix',
	'.xpm' => 'image/x-xpixmap',
	'.xpm' => 'image/xpm',
	'.x-png' => 'image/png',
	'.xsr' => 'video/x-amt-showrun',
	'.xwd' => 'image/x-xwd',
	'.xwd' => 'image/x-xwindowdump',
	'.xyz' => 'chemical/x-pdb',
	'.z' => 'x-compress',
	'.z' => 'x-compressed',
	'.zip' => 'x-compressed',
	'.zip' => 'x-zip-compressed',
	'.zip' => 'zip',
	'.zip' => 'multipart/x-zip',
	'.zoo' => 'octet-stream',
	'.zsh' => 'text/x-script.zsh)'
);




function formatSizeUnits($bytes)
{
	if ($bytes >= 1073741824)
	{
		$bytes = number_format($bytes / 1073741824, 0) . ' gb';
	}
	elseif ($bytes >= 1048576)
	{
		$bytes = number_format($bytes / 1048576, 0) . ' mb';
	}
	elseif ($bytes >= 1024)
	{
		$bytes = number_format($bytes / 1024, 0) . ' kb';
	}
	elseif ($bytes > 1)
	{
		$bytes = $bytes . ' bytes';
	}
	elseif ($bytes == 1)
	{
		$bytes = $bytes . ' byte';
	}
	else
	{
		$bytes = '0 bytes';
	}
	return $bytes;
}



function ValidateDateGuessFormat($date)
{

}

function ValidateDate($date, $format='Y-m-d H:i:s')
{
    $d = DateTime::createFromFormat($format, $date);
    return $d && $d->format($format) == $date;
}

function emptyToNull($str)
{
	if ( trim($str)=='' )
	{
		return null;
	}
	else
	{
		return trim($str);
	}
}


/**
 * Calculates the great-circle distance between two points, with
 * the Haversine formula.
 * @param float $latitudeFrom Latitude of start point in [deg decimal]
 * @param float $longitudeFrom Longitude of start point in [deg decimal]
 * @param float $latitudeTo Latitude of target point in [deg decimal]
 * @param float $longitudeTo Longitude of target point in [deg decimal]
 * @param float $earthRadius Mean earth radius in [m]
 * @return float Distance between points in [m] (same as earthRadius)
 */
function haversineGreatCircleDistance(
  $latitudeFrom, $longitudeFrom, $latitudeTo, $longitudeTo, $earthRadius = 6371000)
{
  // convert from degrees to radians
  $latFrom = deg2rad($latitudeFrom);
  $lonFrom = deg2rad($longitudeFrom);
  $latTo = deg2rad($latitudeTo);
  $lonTo = deg2rad($longitudeTo);

  $latDelta = $latTo - $latFrom;
  $lonDelta = $lonTo - $lonFrom;

  $angle = 2 * asin(sqrt(pow(sin($latDelta / 2), 2) +
    cos($latFrom) * cos($latTo) * pow(sin($lonDelta / 2), 2)));
  return $angle * $earthRadius;
}


function GetConvertedDateTime($expr)
{
	//a partir de lo que recibo en $expr, convierto al formato YYYY-MM-DD hh:mm:ss
	//var_dump($expr);
	if (!$expr || trim($expr)=='')
	{
		return null;	
	}
	
	
	$timestamp = strtotime($expr);
	//var_dump($timestamp);

	$date = new Datetime();
	$date->setTimestamp($timestamp);
	//var_dump($date);
	
	$formatteddate = $date->format('Y-m-d H:i:s');
	//var_dump($formatteddate);
	
	return $formatteddate;
}







function genPdfThumbnail($source, $target)
{
	//$source = realpath($source);
	$target = dirname($source).DIRECTORY_SEPARATOR.$target;
	$im     = new Imagick($source."[0]"); // 0-first page, 1-second page
	$im->setImageColorspace(255); // prevent image colors from inverting
	$im->setimageformat("jpeg");
	$im->thumbnailimage(160, 120); // width and height
	$im->writeimage($target);
	$im->clear();
	$im->destroy();
}






